logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.venable.next: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/h2.db;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 123456
    hikari:
      pool-name: HikariCP
      auto-commit: false

application:
  # Cache configuration
  cache:
    caffeine:
      # By default, objects stay 1 hour in the cache. This sets expireAfterWrite in Caffeine (https://github.com/ben-manes/caffeine/wiki/Eviction#time-based)
      time-to-live-seconds: 3600
      # Number of objects in each cache entry
      max-entries: 100
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: http://localhost:8100, https://localhost:9001
    # Enable CORS when running in GitHub Codespaces
    allowed-methods: '*'
    allowed-headers: '*'
    allow-credentials: true
    max-age: 1800

  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512